apiVersion: resilience.hilios.io/v1alpha1
kind: ContentionReport
metadata:
  name: contention-4
  namespace: default
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      tier: t-4
  windowMinutes: 9
  thresholds:
    cpuStealPercent: 9
    memoryPressureEvents: 5
    throttlingPercent: 9
  recommendOnly: true
