apiVersion: resilience.hilios.io/v1alpha1
kind: ContentionReport
metadata:
  name: contention-8
  namespace: default
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      tier: t-8
  windowMinutes: 13
  thresholds:
    cpuStealPercent: 13
    memoryPressureEvents: 9
    throttlingPercent: 13
  recommendOnly: true
