apiVersion: resilience.hilios.io/v1alpha1
kind: ContentionReport
metadata:
  name: contention-28
  namespace: default
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      tier: t-28
  windowMinutes: 33
  thresholds:
    cpuStealPercent: 13
    memoryPressureEvents: 9
    throttlingPercent: 8
  recommendOnly: true
