apiVersion: resilience.hilios.io/v1alpha1
kind: RebalanceCheck
metadata:
  name: critical-payments-rebalance
  namespace: default
spec:
  targetSelector:
    matchLabels:
      app: payments
      tier: critical
  topologyKey: topology.kubernetes.io/zone
  maxSkew: 1
  dryRun: true
