apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-34
  namespace: default
  labels:
    hilios.io/sample: "34"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 2640
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-34
    namespace: velero
  verificationNamespace: verify-drill-34
