apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-2
  namespace: default
  labels:
    hilios.io/sample: "2"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 720
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-2
    namespace: velero
  verificationNamespace: verify-drill-2
