apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-31
  namespace: default
  labels:
    hilios.io/sample: "31"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 2460
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-31
    namespace: velero
  verificationNamespace: verify-drill-31
