apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-3
  namespace: default
  labels:
    hilios.io/sample: "3"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 780
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-3
    namespace: velero
  verificationNamespace: verify-drill-3
