apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-44
  namespace: default
  labels:
    hilios.io/sample: "44"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 3240
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-44
    namespace: velero
  verificationNamespace: verify-drill-44
