apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-13
  namespace: default
  labels:
    hilios.io/sample: "13"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 1380
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-13
    namespace: velero
  verificationNamespace: verify-drill-13
