apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-12
  namespace: default
  labels:
    hilios.io/sample: "12"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 1320
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-12
    namespace: velero
  verificationNamespace: verify-drill-12
