apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-17
  namespace: default
  labels:
    hilios.io/sample: "17"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 1620
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-17
    namespace: velero
  verificationNamespace: verify-drill-17
