apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-6
  namespace: default
  labels:
    hilios.io/sample: "6"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 960
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-6
    namespace: velero
  verificationNamespace: verify-drill-6
