apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-25
  namespace: default
  labels:
    hilios.io/sample: "25"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 2100
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-25
    namespace: velero
  verificationNamespace: verify-drill-25
