apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-41
  namespace: default
  labels:
    hilios.io/sample: "41"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 3060
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-41
    namespace: velero
  verificationNamespace: verify-drill-41
