apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-7
  namespace: default
  labels:
    hilios.io/sample: "7"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 1020
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-7
    namespace: velero
  verificationNamespace: verify-drill-7
