apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-23
  namespace: default
  labels:
    hilios.io/sample: "23"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 1980
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-23
    namespace: velero
  verificationNamespace: verify-drill-23
