apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-32
  namespace: default
  labels:
    hilios.io/sample: "32"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 2520
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-32
    namespace: velero
  verificationNamespace: verify-drill-32
