apiVersion: resilience.hilios.io/v1alpha1
kind: RecoveryDrill
metadata:
  name: drill-36
  namespace: default
  labels:
    hilios.io/sample: "36"
spec:
  type: RestoreVerification
  cleanup: true
  timeoutSeconds: 2760
  source:
    apiGroup: velero.io
    kind: Backup
    name: backup-36
    namespace: velero
  verificationNamespace: verify-drill-36
