apiVersion: resilience.hilios.io/v1alpha1
kind: RebalanceCheck
metadata:
  name: high-profile-rebalance
  namespace: default
spec:
  targetSelector:
    matchLabels:
      app: profile
      tier: high
  topologyKey: topology.kubernetes.io/zone
  maxSkew: 1
  dryRun: true
