apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: high-cart
  namespace: default
spec:
  targetSelector:
    matchLabels:
      app: cart
      tier: high
      hilios.io/enabled: "true"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 14400
      freshnessSeconds: 86400
