apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: medium-payments
  namespace: default
spec:
  targetSelector:
    matchLabels:
      app: payments
      tier: medium
      hilios.io/enabled: "true"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 14400
      freshnessSeconds: 86400
