apiVersion: resilience.hilios.io/v1alpha1
kind: RebalanceCheck
metadata:
  name: rebalance-4
  namespace: default
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      tier: t-4
  topologyKey: topology.kubernetes.io/zone
  maxSkew: 1
  dryRun: true
