apiVersion: resilience.hilios.io/v1alpha1
kind: RebalanceCheck
metadata:
  name: rebalance-20
  namespace: default
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      tier: t-20
  topologyKey: topology.kubernetes.io/zone
  maxSkew: 2
  dryRun: true
