apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-26
  namespace: default
  labels:
    hilios.io/sample: "26"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "26"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 15600
      freshnessSeconds: 93600
  slo:
    recoveryTimeSeconds: 1560
    maxReplicaSkew: 2
