apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-3
  namespace: default
  labels:
    hilios.io/sample: "3"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "3"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 1800
      freshnessSeconds: 10800
  slo:
    recoveryTimeSeconds: 180
    maxReplicaSkew: 3
