apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-17
  namespace: default
  labels:
    hilios.io/sample: "17"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "17"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 10200
      freshnessSeconds: 61200
  slo:
    recoveryTimeSeconds: 1020
    maxReplicaSkew: 1
