apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-20
  namespace: default
  labels:
    hilios.io/sample: "20"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "20"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 12000
      freshnessSeconds: 72000
  slo:
    recoveryTimeSeconds: 1200
    maxReplicaSkew: 0
