apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-6
  namespace: default
  labels:
    hilios.io/sample: "6"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "6"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 3600
      freshnessSeconds: 21600
  slo:
    recoveryTimeSeconds: 360
    maxReplicaSkew: 2
