apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-19
  namespace: default
  labels:
    hilios.io/sample: "19"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "19"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 11400
      freshnessSeconds: 68400
  slo:
    recoveryTimeSeconds: 1140
    maxReplicaSkew: 3
