apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-22
  namespace: default
  labels:
    hilios.io/sample: "22"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "22"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 13200
      freshnessSeconds: 79200
  slo:
    recoveryTimeSeconds: 1320
    maxReplicaSkew: 2
