apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-7
  namespace: default
  labels:
    hilios.io/sample: "7"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "7"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 4200
      freshnessSeconds: 25200
  slo:
    recoveryTimeSeconds: 420
    maxReplicaSkew: 3
