apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-28
  namespace: default
  labels:
    hilios.io/sample: "28"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "28"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 16800
      freshnessSeconds: 100800
  slo:
    recoveryTimeSeconds: 1680
    maxReplicaSkew: 0
