apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-14
  namespace: default
  labels:
    hilios.io/sample: "14"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "14"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 8400
      freshnessSeconds: 50400
  slo:
    recoveryTimeSeconds: 840
    maxReplicaSkew: 2
