apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-15
  namespace: default
  labels:
    hilios.io/sample: "15"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "15"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 9000
      freshnessSeconds: 54000
  slo:
    recoveryTimeSeconds: 900
    maxReplicaSkew: 3
