apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-1
  namespace: default
  labels:
    hilios.io/sample: "1"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "1"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 600
      freshnessSeconds: 3600
  slo:
    recoveryTimeSeconds: 60
    maxReplicaSkew: 1
