apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-12
  namespace: default
  labels:
    hilios.io/sample: "12"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "12"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 7200
      freshnessSeconds: 43200
  slo:
    recoveryTimeSeconds: 720
    maxReplicaSkew: 0
