apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: sample-25
  namespace: default
  labels:
    hilios.io/sample: "25"
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      sample: "25"
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 15000
      freshnessSeconds: 90000
  slo:
    recoveryTimeSeconds: 1500
    maxReplicaSkew: 1
