apiVersion: resilience.hilios.io/v1alpha1
kind: RebalanceCheck
metadata:
  name: observability-rebalance
  namespace: observability
spec:
  targetSelector:
    matchLabels:
      env: observability
  topologyKey: topology.kubernetes.io/zone
  maxSkew: 1
  dryRun: true
