apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: ml-policy
  namespace: ml
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      env: ml
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 14400
      freshnessSeconds: 86400
