apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: production-policy
  namespace: production
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      env: production
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 14400
      freshnessSeconds: 86400
