{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hilios.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hilios.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hilios.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- if .Values.networkPolicy.ingressNamespaceSelectors }}
        {{- range .Values.networkPolicy.ingressNamespaceSelectors }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml . | nindent 14 }}
        {{- end }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.metricsPort }}
        - protocol: TCP
          port: {{ .Values.healthProbePort }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 6443
        - protocol: TCP
          port: 443
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
