# permissions for end users to view rebalancechecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hilios-operator
    app.kubernetes.io/managed-by: kustomize
  name: rebalancecheck-viewer-role
rules:
- apiGroups:
  - resilience.hilios.io
  resources:
  - rebalancechecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resilience.hilios.io
  resources:
  - rebalancechecks/status
  verbs:
  - get
