# permissions for end users to edit resiliencepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hilios-operator
    app.kubernetes.io/managed-by: kustomize
  name: resiliencepolicy-editor-role
rules:
- apiGroups:
  - resilience.hilios.io
  resources:
  - resiliencepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resilience.hilios.io
  resources:
  - resiliencepolicies/status
  verbs:
  - get
