---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resilience.hilios.io
  resources:
  - contentionreports
  - rebalancechecks
  - recoverydrills
  - resiliencepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resilience.hilios.io
  resources:
  - contentionreports/finalizers
  - rebalancechecks/finalizers
  - recoverydrills/finalizers
  - resiliencepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - resilience.hilios.io
  resources:
  - contentionreports/status
  - rebalancechecks/status
  - recoverydrills/status
  - resiliencepolicies/status
  verbs:
  - get
  - patch
  - update
