apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: qa-policy
  namespace: qa
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      env: qa
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 14400
      freshnessSeconds: 86400
