apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  labels:
    app.kubernetes.io/name: hilios-operator
    app.kubernetes.io/managed-by: kustomize
  name: resiliencepolicy-sample
spec:
  # TODO(user): Add fields here
