apiVersion: resilience.hilios.io/v1alpha1
kind: ResiliencePolicy
metadata:
  name: staging-policy
  namespace: staging
spec:
  targetSelector:
    matchLabels:
      hilios.io/enabled: "true"
      env: staging
  verifications:
    - kind: RestoreVerification
      intervalSeconds: 14400
      freshnessSeconds: 86400
